### ISSUE TITLE
'UnityIntegration' does not exist in the namespace 'Ink' after upgrading to 1.1.15

### ISSUE THREAD

**Issue by olivermarshall2** [inkle/ink-unity-integration#179]
Hi
After upgrading to 1.1.15 I get the following error when compiling;

`error CS0234: The type or namespace name 'UnityIntegration' does not exist in the namespace 'Ink' (are you missing an assembly reference?)`

I'm adding this namespace in VS2019, which seems happy enough, and then using it to control InkPlayerWindow. Visual Studio seems happy enough and can autocomplete functions from UnityIntegration. 

Any ideas why that would be? It worked fine in 1.1.14.

Olly

**Comment by tomkail** [comment]
I'm not sure why it would have worked before! UnityIntegration is an editor namespace, which means you can't include it in game code without #IF UNITY_EDITOR tags.

**Comment by ethanlavinsky46** [comment]
> I'm not sure why it would have worked before! UnityIntegration is an editor namespace, which means you can't include it in game code without #IF UNITY_EDITOR tags.

In that case, how would I handle the use of the "InkFile" namesake?

**Comment by tomkail** [comment]
You need to wrap any editor only code that’s in game code in those
UNITY_EDITOR tags. Do you find you need InkFile.cs your game code? Can you
tell me why?
