### ISSUE TITLE
The name 'InkLibrary' does not exist in the current context error when upgrading to 0.9.61 (Unity 2019)

### ISSUE THREAD

**Issue by patrickklug** [inkle/ink-unity-integration#138]
After importing the new 0.9.61 package I receive the following error:

`Assets\Plugins\Ink\Tools\Startup Window\InkUnityIntegrationStartupWindow.cs(30,132): error CS0103: The name 'InkLibrary' does not exist in the current context`

Are there any upgrade/migration steps from the previous version that I missed?

**Comment by tomkail** [comment]
I cant replicate this! This is using the package attached on the releases page? It sounds like Unity only half finished importing scripts - I takeit a restart doesn't fix it?

**Comment by patrickklug** [comment]
How odd... I managed to get it to run by:
- Reverting everything
- Removing all old ink files (including the Library/ScriptAssemblies/Ink*.ll" files
- Removing the InkLibrary and settings assets.

Then importing the new version again and now it works... No idea what was happening there...
